Name = input("Enter your name: ")
print("Hello, " + Name + "!")
Age = input("Enter your age: ")
print("You are " + Age + " years old.")
Hobby = input("Enter your favorite hobby: ")
print("Your favorite hobby is " + Hobby + ".")
print("Thank you for sharing, " + Name + "!")
print("Have a great day!")
print("Goodbye, " + Name + "!")